language: ruby

rvm:
  - "2.1.1"

bundler_args: --without production development

services:
  - redis-server
  - elasticsearch
  - memcached

before_script:
  - psql -c 'create database campo_test;' -U postgres
  - cp config/config.example.yml config/config.yml
  - cp config/secrets.example.yml config/secrets.yml
  - cp config/database.example.yml config/database.yml
  - "sed -i 's/username:/username: postgres/g' config/database.yml"
