default: &default
  title: 暴走比赛 —— 有趣、有爱的体育社区
  host: localhost:3000 #change to d.baozoubisai.com on production

  mailer:
    # For localhost postfix
    # http://codecampo.com/topics/890
    smtp_settings:
      address: smtp.mailgun.org
      port: 25
      enable_starttls_auto: true
      #domain:
      #user_name: # go to https://mailgun.com
      #password:
      #authentication:
    default_options:
      from: no-reply@d.baozoubisai.com
    default_url_options:
      host: d.baozoubisai.com

  redis:
    host: 127.0.0.1
    port: 6379
    db: 0

  elasticsearch:
    host: localhost:9200

development:
  <<: *default
  admin_emails:
    - zicjin@gmail.com

test:
  <<: *default
  admin_emails:
    - zicjin@gmail.com

production:
  <<: *default

  admin_emails:
    - zicjin@gmail.com
